# Fonts
font_family family="RobotoMono Nerd Font Mono" style="Medium"
font_size 12
modify_font cell_width 90%
draw_bold_text_with_bright_colors yes

# Cursor
shell_integration no-cursor
cursor_shape block
cursor_shape_unfocused block
cursor_blink_interval 0

# Window
window_margin_width 8 12
placement_strategy top-left
confirm_os_window_close 0
hide_window_decorations yes

# Tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+enter no_op
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
tab_bar_style fade
tab_bar_drag_threshold 0
tab_title_template "{index}"
active_tab_font_style none

# macOS
macos_titlebar_color #1e1e1e
macos_show_window_title_in none

# Shift + Enter
map shift+enter send_text all \x1b[13;2u

# Gruvbox colorscheme
cursor                  #ebdbb2
cursor_text_color       background
url_color               #83a598
visual_bell_color       #8ec07c
bell_border_color       #8ec07c
active_border_color     #d3869b
inactive_border_color   #665c54
foreground              #ebdbb2
background              #282828
selection_foreground    none
selection_background    #665c54
active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
color0                  #7c6f64
color1                  #fb4934
color2                  #b8bb26
color3                  #fabd2f
color4                  #83a598
color5                  #d3869b
color6                  #8ec07c
color7                  #bdae93
color8                  #7c6f64
color9                  #fb4934
color10                 #b8bb26
color11                 #fabd2f
color12                 #83a598
color13                 #d3869b
color14                 #8ec07c
color15                 #bdae93
